Repository sunrisesdev/aboard, pull requests merged in 2023-03, with the labels that each got.

#23 feat: add scopes from träweling
  src/pages/api/auth/[...nextauth].ts
Labels: Feature

#24 feat(api): use new route from next
  package-lock.json
  src/app/traewelling/me/route.ts
  src/app/traewelling/stations/[station]/route.ts
  src/app/traewelling/stations/autocomplete/route.ts
  src/app/traewelling/stations/checkin/route.ts
  src/app/traewelling/stations/history/route.ts
  src/app/traewelling/stations/nearby/route.ts
  src/app/traewelling/statuses/[status]/route.ts
  src/app/traewelling/statuses/current/route.ts
  src/app/traewelling/statuses/dashboard/me/route.ts
  src/app/traewelling/statuses/route.ts
  src/app/traewelling/trips/route.ts
  src/components/CheckIn/CheckIn.tsx
  src/components/CheckIn/Search/Search.tsx
  src/components/CheckInDialog/CheckInDialog.tsx
  src/components/DestinationSelector/DestinationSelector.tsx
  src/components/StationSearch/StationSearch.tsx
  src/components/TripSelector/TripSelector.tsx
  src/hooks/useCurrentStatus/useCurrentStatus.ts
  src/hooks/useDepartures/useDepartures.ts
  src/hooks/useRecentStations/useRecentStations.ts
  src/hooks/useStationSearch/useStationSearch.ts
  src/hooks/useStops/useStops.ts
  src/pages/api/me.tsx
  src/pages/api/stations/[station].ts
  src/pages/api/stations/autocomplete.ts
  src/pages/api/stations/checkin.ts
  src/pages/api/stations/history.ts
  src/pages/api/stations/nearby.ts
  src/pages/api/statuses/[status].tsx
  src/pages/api/statuses/current.tsx
  src/pages/api/statuses/dashboard/me.tsx
  src/pages/api/statuses/index.ts
  src/pages/api/trips/index.tsx
  src/utils/api/createErrorResponse.ts
  src/utils/api/createResponse.ts
  src/utils/api/getSafeUrlParams.ts
Labels: Feature

#29 feat: add dashboard related "placeholder" components
  src/app/traewelling/statuses/route.ts
  src/components/Statuses/Statuses.module.scss
  src/components/Statuses/Statuses.tsx
  src/hooks/useDashboard/useDashboard.ts
  src/page-templates/dashboard.tsx
  src/traewelling-sdk/functions/status.ts
  src/traewelling-sdk/types.ts
Labels: Feature

#32 feat: add initial functions to add user pages
  package-lock.json
  package.json
  src/app/[username]/page.tsx
  src/components/Statuses/Statuses.tsx
  src/traewelling-sdk/functions/user.ts
  src/traewelling-sdk/types.ts
  tsconfig.json
Labels: Feature

#37 feat: create seperate route component
  src/components/CheckIn/Panel/Panel.tsx
  src/components/Route/Route.module.scss
  src/components/Route/Route.tsx
  src/components/Route/types.ts
  src/components/StatusDetails/StatusDetails.module.scss
  src/components/StatusDetails/StatusDetails.tsx
  src/utils/parseSchedule.ts
Labels: Improvement

#43 fix: add and remove cache to tr api
  src/traewelling-sdk/functions/auth.ts
  src/traewelling-sdk/functions/status.ts
  src/traewelling-sdk/functions/trains.ts
  src/traewelling-sdk/functions/user.ts
Labels: Bug

#44 feat: add status page pre fetching and dashboard
  src/app/status/[id]/page.tsx
  src/app/status/page.tsx
  src/components/StatusDetails/StatusDetails.tsx
  src/components/StatusDetails/types.ts
  src/components/Statuses/Statuses.tsx
Labels: Improvement

#48 feat: add umami for anonymous tracking our users ❤️
  next.config.js
  src/app/layout.tsx
  src/components/CheckIn/CheckIn.tsx
  src/hooks/useUmami/types.ts
  src/hooks/useUmami/useUmami.ts
  src/scripts/UmamiScript/UmamiScript.tsx
  src/types/global.d.ts
Labels: Feature

#49 refactor: update CurrentStop component
  src/app/status/[id]/page.tsx
  src/components/Route/Route.module.scss
  src/components/StatusDetails/StatusDetails.module.scss
  src/components/StatusDetails/StatusDetails.tsx
  src/components/StatusDetails/types.ts
  src/helpers/getStopsAfter.ts
  src/hooks/useStops/useStops.ts
  src/styles/globals.css
Labels: Improvement

#50 feat: add accent component
  src/components/Accent/Accent.module.scss
  src/components/Accent/Accent.tsx
  src/components/Accent/types.ts
  src/components/CheckIn/DestinationStep/DestinationStep.module.scss
  src/components/CheckIn/DestinationStep/DestinationStep.tsx
  src/components/CheckIn/FinalStep/FinalStep.module.scss
  src/components/CheckIn/FinalStep/FinalStep.tsx
  src/components/CheckIn/TripStep/TripStep.tsx
  src/components/FullscreenLoading/FullscreenLoading.module.scss
  src/components/Route/Route.module.scss
  src/components/StatusDetails/StatusDetails.module.scss
  src/components/StatusDetails/StatusDetails.tsx
  src/hooks/useAccentColor/useAccentColor.ts
  src/hooks/useAppTheme/useAppTheme.ts
  src/styles/globals.css
Labels: Bug, Improvement

#52 feat: custom line colors
  src/components/Accent/Accent.tsx
  src/components/Accent/types.ts
  src/components/CheckIn/CheckIn.tsx
  src/components/CheckIn/CurrentStatus/CurrentStatus.module.scss
  src/components/CheckIn/CurrentStatus/CurrentStatus.tsx
  src/components/CheckIn/DestinationStep/DestinationStep.module.scss
  src/components/CheckIn/DestinationStep/DestinationStep.tsx
  src/components/CheckIn/FinalStep/FinalStep.module.scss
  src/components/CheckIn/FinalStep/FinalStep.tsx
  src/components/CheckIn/Panel/Panel.module.scss
  src/components/CheckIn/TripStep/TripStep.module.scss
  src/components/CheckIn/TripStep/TripStep.tsx
  src/components/CheckIn/TripStep/types.ts
  src/components/LineIndicator/LineIndicator.module.scss
  src/components/LineIndicator/LineIndicator.tsx
  src/components/LineIndicator/types.ts
  src/components/Route/Route.module.scss
  src/components/StatusDetails/StatusDetails.module.scss
  src/components/StatusDetails/StatusDetails.tsx
  src/components/ThemeProvider/ThemeProvider.module.scss
  src/components/ThemeProvider/ThemeProvider.tsx
  src/components/ThemeProvider/types.ts
  src/helpers/getContrastColor.ts
  src/helpers/getLineTheme/consts.ts
  src/helpers/getLineTheme/getLineTheme.ts
  src/hooks/useAppTheme/useAppTheme.ts
  src/styles/_index.scss
  src/styles/_product-colors.scss
Labels: Feature
