Repository sunrisesdev/aboard, pull requests merged in 2023-04, with the labels that each got.

#60 feat: extend status details page and add button to exit it
  src/components/StatusDetails/StatusDetails.module.scss
  src/components/StatusDetails/StatusDetails.tsx
  src/utils/formatDate.ts
  src/utils/formatTime.ts
  src/utils/parseSchedule.ts
Labels: Improvement

#63 fix: adjust next cache
  src/traewelling-sdk/functions/auth.ts
  src/traewelling-sdk/functions/trains.ts
  src/traewelling-sdk/functions/user.ts
Labels: Bug

#66 feat: add rename from user page and add better statuses loading
  src/app/traewelling/user/[username]/statuses/route.ts
  src/app/u/[username]/layout.tsx
  src/app/u/[username]/page.tsx
  src/app/u/page.tsx
  src/components/Profile/Statuses/Statuses.tsx
  src/components/Statuses/Statuses.tsx
  src/hooks/useUserStatuses/useUserStatus.ts
Labels: Improvement, Feature
